services:
  db:
    image: postgres
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "mysecretpassword"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  

  web:
    build: .
    security_opt:
      - seccomp:unconfined
      # - seccomp:chrome.json
    ports:
      - "1336:1337"
    environment:
      - env=pi
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgresqldata:
  
