services:
  db:
    image: postgres
    volumes:
      - postgresqldata:/var/lib/postgresql/data
    expose:
      - '5432'
    environment:
      PGUSER: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'mysecretpassword'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'postgres']
    restart: always

  web:
    build: .
    volumes:
      - pdfs:/usr/app/Thalia/websites/kras/data/pdfs
    security_opt:
      - seccomp:unconfined
    ports:
      - '1336:1337'
    environment:
      - NODE_ENV=docker
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  postgresqldata:
  pdfs:
